### ISSUE TITLE
[Fidus] Separate development and deployment environment

### ISSUE THREAD

**Issue by StijnArnauts** [CIRB/devbox#1]
A week or so ago, I installed and evaluated the devbox to see if the Fidus/PSB team could migrate to it. I found a few issues that stand in the way of our adoption, mostly related to how we use puppet.

The CICD box has not been designed as the main development environment: as I understand it the idea is to develop in Eclipse on the host machine, and only use the devbox to maintain the CICD configuration (puppet, rpm-builder, jenkins pipeline)

However, for the Fidus/PSB projects we have created puppet scripts to automatically roll out a complete development environment including our servers, database, keystores, data, etc. Obviously we can't do that on our Windows host machine since the puppet configuration has been tailored to a Linux OS (it expects a Linux file system, and depends on some Linux-only configuration files).

We also can't do roll out our servers with puppet on the devbox, because the devbox does not have the yum package manager, so our scripts won't work. By default, the devbox also does not have puppet installed.

So if we start using the devbox for maintaining our puppet configuration, we would still require a seperate VM with nix installed as our main development environment. If that is the case, I see few benefits in using the devbox at all. Especially compared to the disadvantage that the whole team needs to get used to a new OS, package manager, window manager, and lack of a proper graphical file explorer.

For our team, I see three points which I would like to see resolved:
- Enable support for the yum package manager
- Enable support for an (optional?) more user-friendly graphical windows manager

Nice to have would be:
- Install puppet by default

**Comment by pradermecker** [comment]
We will handle this issue by separating the development and deployment environment from the current CentOS box.

When this separation is effective, we will replace the development part of the current CentOS box with the devbox and keep the deployment environment (configured with puppet). This deployment VM could be embedded in a docker if it is more convenient.

**Comment by pradermecker** [comment]
Closing because the fix doesn't depend on this project
