### ISSUE TITLE
How to add a new tool?

### ISSUE THREAD

**Issue by tbrouhier** [CIRB/devbox#19]
The system has two configuration files to install packages: configuration.nix which is the system configuration, shared for everyone and local-configuration.nix the entry point you are looking for. 

To find out the name of the package, you can run a search there: https://nixos.org/nixos/packages.html.

There is a default local-configuraiton.nix file and it is located in /etc/nixos. As root, edit it by adding the package you want. E.g. with nautilus:
```
environment.systemPackages = with pkgs; [
    (eclipses.eclipseWithPlugins {
       eclipse = eclipses.eclipse-sdk-452;
       plugins = [ ];
     })
    firefox
    gitAndTools.tig
    # geany
    gnome3.nautilus
  ];
```
Then, as root, run the nixos-rebuild switch to install the package.

Finally, if it worked, copy the local-configuration.nix to your ROOT_DIR so you keep your changes in case you need to destroy the current box and create a new one. This file will be picked up during initialization.

**Comment by HybZ** [comment]
Hey, how can I install Intellij in a DevBOX?

**Comment by tbrouhier** [comment]
Hello. Could you open an issue about that? Thanks

**Comment by pradermecker** [comment]
README updated accordingly
