### ISSUE TITLE
params.sh comments may be a great improvement

### ISSUE THREAD

**Issue by HybZ** [CIRB/devbox#2]
Hi, just installed the devbox following the README on github. params.sh is an optional part of the installation but it has a huge impact on the outcome because without it the pupet-stack-* is not configured during provisioning.
It's not really clear when reading the "Quick first time setup" that params.s should be in the same folder as Vagrantfile.
It could be a great addition if some comments were put inside the default params.sh so anyone can configure.

**Comment by pradermecker** [comment]
I have updated the documentation in https://github.com/CIRB/devbox/commit/f303125bdea38401da24d85078dfd6b2544323db and released in 2.4.4.

Would you mind doing a `vagrant provision --provision-with user` and then `F1`.

Thanks for your comment. Let me know if you see further improvements.

**Comment by pradermecker** [comment]
I still need to add some comments. Will do shortly.

**Comment by pradermecker** [comment]
Fixed with a93dc089d59e4315de2d9e7827cd8934f00aded
