### ISSUE TITLE
Where can we find the devbox roadmap?

### ISSUE THREAD

**Issue by tbrouhier** [CIRB/devbox#22]
We currently have no roadmap other than the two major versions by year that we promised and some support time every month. 

These major upgrades follow the nixos major versions. They will be available around March/April and September/October. 

We will use your feedback to determine the actions to take and improvements to make. 

Feel free to participate to its development, you can always PR changes that might be useful to everyone.

**Comment by pradermecker** [comment]
https://github.com/CIRB/devbox/projects/1
