### ISSUE TITLE
What to do to keep the devbox state through destroy(s)

### ISSUE THREAD

**Issue by tbrouhier** [CIRB/devbox#23]
The goal is keeping the devbox stateless and having all configuration and action reproducible from sources. The only state that should happen on the devbox would be not yet pushed changes in one of your repositories.

Here are few entry points for configuration:
- the system configuration: configuration.nix
- your own installed packages: local-configuration.nix
- the pointers to the repositories you need to clone: the mr repository (by default: https://github.com/CIRB/vcsh_mr_template)
- the user configuration files (called dotfiles): a github repository (by default: https://github.com/CIRB/devbox-dotfiles)
- your ROOT_DIR that contains ssh-keys, params, local-configuration,...

**Comment by pradermecker** [comment]
What do you want to do with this issue ?
Can we close it now given the updated README ? If we can't would you mind updating the doc accordingly ?
