### ISSUE TITLE
How to configure mr files by user?

### ISSUE THREAD

**Issue by tbrouhier** [CIRB/devbox#26]
The mr files are pointers to repositories you want to clone. 

By default, we provide a repository with all available puppet/salt projects: https://github.com/CIRB/vcsh_mr_template

If you need a repository that is not in the .config/mr/available.d folder, you could:
- ask us to add it to the generic mr pointers by a github issue or a pull request
- fork the mr repository and have your own pointers

The latter is really empowering you but makes the maintenance more complicated as you will have to keep up with the master yourself. 

**Note**: for now, if you work in several projects, as you can't specify more than one stack at init, you will have to make mr files enabled (create symlink, see https://github.com/CIRB/devbox/blob/master/README.adoc#projects). A solution to that would be to fork the mr repository but this initialization behavior will in change in the devbox 3.0 to allow a list of stacks/repositories.

**Comment by pradermecker** [comment]
README updated acccordingly in v3.1
