### ISSUE TITLE
Eclipse: how to add plugin?

### ISSUE THREAD

**Issue by tbrouhier** [CIRB/devbox#28]
There is an entry point for that in the devbox: _local-configuration.nix_ that you can find in /etc/nixos. 

You can find more information on installing packages in the README or in this other question: https://github.com/CIRB/devbox/issues/19

If you consider a plugin to be needed by everyone, please propose it to the community (github issue or pull request) and it might end up in the default configuration.

**Comment by pradermecker** [comment]
Added to FAQ
