### ISSUE TITLE
Provide a default and persistent Eclipse configuration

### ISSUE THREAD

**Issue by tbrouhier** [CIRB/devbox#29]
We do the assumptions that the tools we are using are supporting configuration files. In that case, keeping such configuration from a box to another should simply be a question of putting the files in a source control system. 

Should it be a default available to anyone or in a private repository is a question for every case. Even if we strive for a devbox as generic as possible.

**Comment by pradermecker** [comment]
v3.2 will attempt to add a default config for Eclipse.
We can create a mr file just as we do for xmonad that can be overridden

**Comment by pradermecker** [comment]
Fixed with https://github.com/CIRB/devbox-dotfiles/commit/b863191ce6f14dfccb4df50c0b5a162229c29f3f
