### ISSUE TITLE
Not possible to edit git global config in devBox

### ISSUE THREAD

**Issue by mlefevre** [CIRB/devbox#30]
Having recently updated my devbox from v1.1 to v2.5, it seems to be impossible to edit the git configuration.
When using command `git config -e ` or `git config --global -e`, I get following error message: 
```
error: cannot run nvim: No such file or directory
error: unable to start editor 'nvim'
```
The git config seems ok as `git config -l` still answers correctely

**Comment by pradermecker** [comment]
Fixed with https://github.com/CIRB/devbox-dotfiles/commit/f715ca8c4af6b93e04d0c7f0cd2042ba1cd5d6d3
