### ISSUE TITLE
How to add a tool to the Menu "<Super> p"?

### ISSUE THREAD

**Issue by lbuyse** [CIRB/devbox#31]
How can i add an installed tool or package (custom or not) like for ex. nautilus  to the menu that is shown when pressing "<Super> p" keys.

**Comment by pradermecker** [comment]
@lbuyse you add `nautilus` in that line: https://github.com/CIRB/devbox-dotfiles/blob/master/.xmonad/xmonad-taffybar.hs#L39

**Comment by lbuyse** [comment]
Works great thanks , for my part you can add nautilus in the v3
