### ISSUE TITLE
[IAM] Keystore Explorer native in the devbox.

### ISSUE THREAD

**Issue by lbuyse** [CIRB/devbox#34]
It would be nice if the Keystore Explorer tool would be natively installed on the Devbox.
Not only for the IAM team but i guess a lot of other people on projects work with keys , certificates and keystores/truststores. Keystore Explorer makes that very easy.
See manual installation on linux : http://keystore-explorer.org/downloads.html

**Comment by pradermecker** [comment]
fixed in https://github.com/CIRB/nixpkgs-config/commit/70ad761868b36f70f75c5016741996fdd87d7c99

@lbuyse when devbox-4.x is out, you will be able to uncomment this line to get it:
https://github.com/CIRB/devbox/blob/master/user/config/box.dhall#L30

**Comment by lbuyse** [comment]
Fantastic!! i'll wait for devbox 4 then :)
