### ISSUE TITLE
Clear command doesn't work on remote ssh console

### ISSUE THREAD

**Issue by lbuyse** [CIRB/devbox#45]
whenever i connect ssh to my machines in the devbox and i try to run the command `clear` to clear console screen i get this error : 
```
[lbuyse@iam-web ~]$ clear
'xterm-termite': unknown terminal type. 
```
Problem exists since 3.1 i guess (termite terminal??)

**Comment by pradermecker** [comment]
Here is a fix.

Write a zsh function like so:
```
λ ~ → cat .zsh_custom/fun.zsh 

function sshi () {
    TERM=xterm ssh -A -i ~/.ssh/youruser_rsa youruser@$1
}
```
The important bit is `TERM=xterm`

A better solution might be to set $TERM with `xterm-terminfo` but the above workaround works.
