### ISSUE TITLE
Mise à jour de la doc d'install

### ISSUE THREAD

**Issue by abernardinello** [CIRB/devbox#46]
Salut,

Vous devriez mettre à jour,  j’ai perdu pas mal de temps avec ça :

mkdir config
curl -o config/box**.dhall** https://raw.githubusercontent.com/CIRB/devbox/3.4.2/user/config/box.dhall
curl -o config/shell**.dhall** https://raw.githubusercontent.com/CIRB/devbox/3.4.2/user/config/shell.dhall

**Comment by pradermecker** [comment]
@abernardinello Oui j'ai réalisé cette erreur en l'installant moi-même aujourd'hui ;-)

C'est donc corrigé. Un grand merci !
