### ISSUE TITLE
Improve doc to troubleshooting issues of encoding with params.sh

### ISSUE THREAD

**Issue by tbrouhier** [CIRB/devbox#5]
While creating the params.sh on Windows host, user could end up with badly encoded file resulting in errors. Please add warning in documentation and improve mechanism

**Comment by pradermecker** [comment]
Done yesterday evening ;-)

Could you check if it is alright for you ?

**Comment by pradermecker** [comment]
I have just release the fix. Can you do `vagrant provision --provision-with user`, then `F1` on the box ?

I don't think this is a bug ... but we need to improve the process in v3.
