### ISSUE TITLE
Ubuntu instead of nixos?

### ISSUE THREAD

**Issue by lbuyse** [CIRB/devbox#55]
Hello ,

What about a devbox with ubuntu that can also be used to do project development and is less lightweight?
For example i can't make angular cli nodejs work in nixos : 
`λ  src/main/angular at  master !
→ sudo npm install -g @angular/cli                                                                                                                                                                         127 ↵
npm WARN checkPermissions Missing write access to /nix/store/ikcsm8h0gbqs6b065846kadp2kiyz7y1-nodejs-8.11.4/lib/node_modules
npm ERR! path /nix/store/ikcsm8h0gbqs6b065846kadp2kiyz7y1-nodejs-8.11.4/lib/node_modules
npm ERR! code EROFS
npm ERR! errno -30
npm ERR! syscall access
npm ERR! rofs EROFS: read-only file system, access '/nix/store/ikcsm8h0gbqs6b065846kadp2kiyz7y1-nodejs-8.11.4/lib/node_modules'
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-29T16_27_25_085Z-debug.log`

It would be nicer if we can chose ourself to install for ex. spring sts instead of normal eclipse etc...
I have the feeling nixos is a little too lightweight or maybe not mainstream enough...

**Comment by pradermecker** [comment]
I probably won't switch from nixos to ubuntu because there is no way to get the same declarative and persistent configuration with Ubuntu.

But I can try to support both angular/cli and spring sts. If you could make two separated issues for these that would be nice.

**Comment by pradermecker** [comment]
Closing this for now. Don't hesitate to open separated issue for angular/cli or spring sts if you want them.
